import type { Metadata } from 'next';
import { funnel_Sans } from '@/lib/fonts.config';
import MenuButton from '@/components/menu-button';
import './globals.css';

export const metadata: Metadata = {
	title: 'Samadhi Gunasinghe | Creative Web Developer and Designer',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body className={`${funnel_Sans.className} antialiased`}>
				<MenuButton />
				{children}
			</body>
		</html>
	);
}
